### ISSUE TITLE
Gists

### ISSUE THREAD

**Issue by grawlinson** [martenbjork/github-xp#10]
https://github.com/martenbjork/github-xp/blob/ee8954b062257913dc6a7bc6f08fe21f459aa05d/manifest.json#L9

Am I right in assuming that this wouldn't work on `gist.github.com` due to the above line?

**Comment by martenbjork** [comment]
Yup, that's correct. It's because there's a lot of random stuff on GitHub's subdomains (like blogs) that uses a completely different front end framework.
