### ISSUE TITLE
ctrl + alt + del

### ISSUE THREAD

**Issue by felippepuhle** [martenbjork/github-xp#11]
tried to press `ctrl + alt + del` but nothing happens... what can I do without this?

**Comment by ronal2do** [comment]
+1

**Comment by martenbjork** [comment]
As much as I love this suggestion, it's a bit beyond the scope of the extension.

Closing issue, but with ❤️.

**Comment by felippepuhle** [comment]
@martenbjork i was kidding... sorry 😅
