### ISSUE TITLE
Suggestion: Replace 404s with BSOD

### ISSUE THREAD

**Issue by MettaProgrammer** [martenbjork/github-xp#12]
In true windows fashion, it would be great to see all error pages replaced with the classic blue screen of death.

**Comment by gaby-de-wilde** [comment]
I couldn't get image `#parallax_error_text` to move to the left top but you can easily `padding` the image out of sight and _replace_ its container with a `background-image`.

**Comment by martenbjork** [comment]
Lol, sure! :) GitHub's 404 page is a bit of a hack itself, so it's hard to re-style, but it looks like this now:

![skarmavbild 2018-06-06 kl 10 32 51](https://user-images.githubusercontent.com/875708/41026563-2a45c0fc-6975-11e8-91c1-32efbb4b7c6f.jpg)

**Comment by martenbjork** [comment]
Added some glitchyness and fixed the color:

![screen recording claquette](https://user-images.githubusercontent.com/875708/41027043-678f9450-6976-11e8-84c6-55540a97e5e0.gif)

**Comment by vaniakosmos** [comment]
doesn't look like original win-xp bsod
![image](https://user-images.githubusercontent.com/16745500/41027285-4607d3de-697f-11e8-9c1e-517caf628bc6.png)

maybe try something modern, like this one
![image](https://user-images.githubusercontent.com/16745500/41027223-232266e0-697f-11e8-9fc8-65b98a5da3a0.png)
