### ISSUE TITLE
Use xp folder and file icons

### ISSUE THREAD

**Issue by JuanPotato** [martenbjork/github-xp#14]
Would add to the overall feel, shouldn't be too hard to [find](https://gothago229.deviantart.com/art/Windows-XP-icons-213276853) a collection somewhere

**Comment by gaby-de-wilde** [comment]
finding is easy, replacing the svg images wiht css not so much.

See for yourself: https://pastebin.com/34Fr3mGy

Then, lets pretend this never happened.

**Comment by martenbjork** [comment]
It's a good suggestion! Thanks for having a go at it @gaby-de-wilde. I ended up with the same conclusion as you did. We could solve this with JS, but I would like the project to stay CSS only so that people feel safe(er) using the extension.
