### ISSUE TITLE
Pinned repositories display in one column instead of two

### ISSUE THREAD

**Issue by vaniakosmos** [martenbjork/github-xp#18]
firefox 60.0.1

<img width="995" alt="screen shot 2018-06-06 at 11 07 28" src="https://user-images.githubusercontent.com/16745500/41025187-ecd49630-6979-11e8-9f43-bcc621f81aa4.png">

should be:
<img width="995" alt="screen shot 2018-06-06 at 11 07 49" src="https://user-images.githubusercontent.com/16745500/41025188-ed30e980-6979-11e8-9683-9975d2701e20.png">

**Comment by vaniakosmos** [comment]
`.pinned-repo-item { width: 350px }` fixed it

**Comment by martenbjork** [comment]
Thanks a bunch! Fixed! :)
