### ISSUE TITLE
CSS broken on the issue tab

### ISSUE THREAD

**Issue by deuzu** [martenbjork/github-xp#2]
This could be displayed as a Windows XP error  :D
![image](https://user-images.githubusercontent.com/234792/40967602-befe916e-68b3-11e8-8f8e-5373882aa139.png)

The edited button seems a bit lost in the top left corner =(
![image](https://user-images.githubusercontent.com/234792/40967874-7d9be464-68b4-11e8-9616-1f2d54d30333.png)

Awesome work !! :heart: 
Looking forward the Vista theme :1st_place_medal:

**Comment by martenbjork** [comment]
Thanks @deuzu! ❤️ I think I've fixed it now, but it's a very shady process of guessing CSS selectors, so we'll have to see :D
