### ISSUE TITLE
BSOD on Unicorn (This page is taking way too long to load.)

### ISSUE THREAD

**Issue by sulfo** [martenbjork/github-xp#23]
Right now GIthub is having some problems (Microsoft??), so I'm having the unicorn everywhere.

Therefor I would really enjoy a BSOD unicorn, or something similar. 
Just a plain blue background is fine for me ;)

**Comment by martenbjork** [comment]
Just looked at the source code of the unicorn page. Doesn't seem to be any selectors to work with :( 

https://github.com/503.html
