### ISSUE TITLE
The title bar and the taskbar are unfixed 

### ISSUE THREAD

**Issue by Moegay** [martenbjork/github-xp#27]
When using the Octotree plug-in,The title bar and the taskbar are unfixed 
![image](https://user-images.githubusercontent.com/23082541/41045248-990907c8-69da-11e8-82cc-30d1a21f4948.png)
Browser's  : Chrome 68.0.3440.7 dev
Extensions : Octotree

**Comment by martenbjork** [comment]
Nice catch, I'll look into it later!
