### ISSUE TITLE
[BUG] Wrong title position when using with octotree

### ISSUE THREAD

**Issue by williamokano** [martenbjork/github-xp#34]
The title is misplaced when octotree sidebar is open

https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=pt-BR

![image](https://user-images.githubusercontent.com/5909442/41053304-898dcd86-6991-11e8-882e-fe38e486ccb5.png)

**Comment by martenbjork** [comment]
Duplicate of #27 . I'll fix it! :)
