### ISSUE TITLE
Bug?: is '-webkit-font-smoothing: none;' intentional?

### ISSUE THREAD

**Issue by neo** [martenbjork/github-xp#42]
https://github.com/martenbjork/github-xp/blob/master/xp.css#L9

This is so far the only thing preventing me from actually using it for a long term. Just wondering is it intentional to disable `antialiased`?

**Comment by martenbjork** [comment]
Yes! I'm aiming for the full XP experience, including font rendering that makes you want to cry :)

**Comment by neo** [comment]
lol fine

**Comment by duanhong169** [comment]
I'm crying😂
