### ISSUE TITLE
The navigation is not well aligned when you head to marketplace

### ISSUE THREAD

**Issue by jrharshath** [martenbjork/github-xp#44]
<img width="1920" alt="screen shot 2018-06-06 at 2 16 31 pm" src="https://user-images.githubusercontent.com/85807/41065813-b5d589b2-6994-11e8-9542-7512d713db60.png">

**Comment by martenbjork** [comment]
Fixed! 
![skarmavbild 2018-06-07 kl 11 13 58](https://user-images.githubusercontent.com/875708/41090169-e8eabf3e-6a43-11e8-8fbc-49428359acbb.jpg)
