### ISSUE TITLE
Feature request: Convert it to a webpack project

### ISSUE THREAD

**Issue by teanoon** [martenbjork/github-xp#45]
Easier to maintain.

**Comment by JPeer264** [comment]
This project is mainly one `.css` file. What is the added value of webpack?

**Comment by teanoon** [comment]
So we can use sass.
And it has base64 encoded images and they are very long 😝 Webpack can import images as base64. Easier to write as well.

**Comment by martenbjork** [comment]
Let's keep this discussion open :) Honestly, since this project is mostly a joke, I think (pray) that there won't be too much maintenance going forward.

(And I do think it's quite nice that anyone can suggest changes to the CSS without having to open their terminals and type npm install.)

**Comment by JPeer264** [comment]
I agree with @martenbjork, it is way easier to have just the css file without any build step in between. Furthermore, Windows XP is simple and classy - so the repo should reflect this style too, right? :)

**Comment by martenbjork** [comment]
Closing for now :)
