### ISSUE TITLE
Feature request: Disable Clippy

### ISSUE THREAD

**Issue by Qu4tro** [martenbjork/github-xp#53]
I'm enjoying this new aspect of github. It reminds me that I'm using a microsoft product. 

However... Clippy...is...not...helpful. Let's keep it at that. Can we have an option to disable it?

**Comment by justinjk007** [comment]
Atleast make an option to make it a bit smaller

**Comment by martenbjork** [comment]
I get it! Clippy never was very helpful…

I have no plans to add options to the plugins, but it's very “easy” to download the repo and run it locally in Chrome. Just remove the clippy-related CSS in xp.css and you're good to go.
