### ISSUE TITLE
MS Edge Version

### ISSUE THREAD

**Issue by NanhuGITHUB** [martenbjork/github-xp#54]
Make a Version for Microsoft Edge.

**Comment by NanhuGITHUB** [comment]
#52

**Comment by erikpt** [comment]
You can use Tampermonkey (https://tampermonkey.net/?browser=edge) with the userscript I posted in Pull request #9 to enable this in Edge or use Greasemonkey on Firefox.

**Comment by martenbjork** [comment]
I haven't got the time to implement this, but forks are more than welcome! :)

**Comment by NanhuGITHUB** [comment]
@erikpt Created a UserScript
