### ISSUE TITLE
Font aliased

### ISSUE THREAD

**Issue by martinlatrille** [martenbjork/github-xp#56]
The font renders super aliased on my screen:
- MacOS 10.12.6
- Chrome 66.0.3359.181

![screen shot 2018-06-07 at 17 17 22](https://user-images.githubusercontent.com/7400712/41132596-dd3b7b96-6a76-11e8-9429-17adfe43a00b.png)

**Comment by hayzey** [comment]
It's been addressed in this PR: https://github.com/martenbjork/github-xp/pull/55

**Comment by martenbjork** [comment]
Alas friends, this is all part of the joke. See #3.
