### ISSUE TITLE
Feature Request: Add XP error sound

### ISSUE THREAD

**Issue by Majkl578** [martenbjork/github-xp#6]
This is essential component of XP, without this, it's incomplete.
Proposal: Play anytime when clicking outside cliclable elements (clicling outside links, inside text, on disable buttons).

https://www.youtube.com/watch?v=iqztd7uMvVI

**Comment by martenbjork** [comment]
Haha, as much as I love this idea, I don't want to inject anything other than CSS. I want people to be able to trust the extension without having to read too much source code :)
