### ISSUE TITLE
font issue

### ISSUE THREAD

**Issue by zmpyzmpy** [martenbjork/github-xp#63]
I keep getting this error:

Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAEzMABMAAAAAezAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABqAAAABwAAAAcbHuVbkdERUYAAAHEAAAAHAAAAB4AJwCWR1BPUwAAAeAAAAXZAAAJpGVqwf1HU1VCAAAHvAAAACwAAAAwuP+4/k9TLzIAAAfoAAAAXAAAAGDY59IiY21hcAAACEQAAAFPAAACCqtY6vFjdnQgAAAJlAAAADcAAABIJlMGxGZwZ20AAAnMAAAFqAAAC5fbFNvwZ2FzcAAAD3QAAAAIAAAACAAAABBnbHlmAAAPfAAAM+AAAE6g3+9Ct2hlYWQAAENcAAAAMwAAADYIhrfwaGhlYQAAQ5AAAAAhAAAAJA5MBZ5obXR4AABDtAAAAboAAAJA90wzR2xvY2EAAEVwAAABEAAAASIQ0fv8bWF4cAAARoAAAAAgAAAAIAG7Ac1uYW1lAABGoAAABEkAAAx4Zctph3Bvc...c8CSSSRDIppJJGOhlkkkU2OeSSRz4FFFJEMSWUUkY5FWjoOHFRiZsqqqmhljrqaaCRJpppwRP4rg0v7fjooJMuuumhlz76GWCQIYYZYZQxxplgkimmmWGWOeZZYJElCeaAQy4445hLsXDEKZ9c8cYH72KVEAkVm4RJuESIXSLFIVESLTESyw23PPDIC3fc88q1xPHEs8RLAieSaFnb3N9Z163+rQ1N07xGdBnRoym9vzoDe6WudCpdykqlW1mlrFbWKGuVHkNd3dV12+rGmn93ZXlpb90YOX2Gbp+53b+7/RfcvrYfygRb7gAAAHjaY/DewXAiKGIjI2Nf5AbGnRwMHAzJBRsZ2Jw2M0gzMWiBWFsVGfk4mDggbCUGCTYwm8NpN0cD8wEGJgZOII/LaTcDA4MDhMfM4LJRhbEjMGKDQ0fERuYUl41qIN4ujgYGRhaHjuSQCJCSSCAAGifAwcSjtYPxf+sGlt6NTECdrCkuALy2JpcAAVT4eScAAA==' because it violates the following Content Security Policy directive: "font-src assets-cdn.github.com".

It seems that the font was not correctly loaded.
![image](https://user-images.githubusercontent.com/6594919/41210870-9ea17762-6d66-11e8-9380-c324db06a2e2.png)

![image](https://user-images.githubusercontent.com/6594919/41210818-76051c82-6d66-11e8-9b5d-b1bd741a0d7e.png)

**Comment by martenbjork** [comment]
@zmpyzmpy Yup, that doesn't appear to be from this plugin. Hope you get it sorted!
