### ISSUE TITLE
ugly font on macos

### ISSUE THREAD

**Issue by glensc** [martenbjork/github-xp#64]
![image](https://user-images.githubusercontent.com/199095/41217408-6df5a418-6d60-11e8-9df3-feb03a86b8e9.png)

**Comment by martenbjork** [comment]
Duplicate of #3 :)

**Comment by martenbjork** [comment]
It's intentional :) #42

**Comment by glensc** [comment]
oh. i thought it requires some xp font which is not available on macos and no fallback provided.
