### ISSUE TITLE
There are some problems with the font on the mac

### ISSUE THREAD

**Issue by wyfang** [martenbjork/github-xp#66]
![qq20180611-164721](https://user-images.githubusercontent.com/17900420/41221605-2f2b89aa-6d97-11e8-856f-eca2026e8467.png)

**Comment by d1monster** [comment]
Looks very XP-ly =) but yea.. Would be nice to fix this issue.

**Comment by martenbjork** [comment]
It's intentional :) See #42

**Comment by wyfang** [comment]
@martenbjork But why not see this effect on Windows 10?
