### ISSUE TITLE
If the addon is taken down, please archive it.

### ISSUE THREAD

**Issue by chaziz94** [martenbjork/github-xp#76]
This title says it all.

**Comment by TheAwesome98-Real** [comment]
Oh, so we’re not allowed to work on plugins that aren’t on the store anymore? Bit stupid innit mate.

**Comment by chaziz94** [comment]
> Oh, so we’re not allowed to work on plugins that aren’t on the store anymore? Bit stupid innit mate.

i was 12 when I wrote this issue.

**Comment by TheAwesome98-Real** [comment]
ok
