### ISSUE TITLE
Feature Request: Clippy!

### ISSUE THREAD

**Issue by FredKSchott** [martenbjork/github-xp#8]
Just hanging out in the bottom-right corner, maybe bouncing around.

"It looks like you're writing a PR description!" :)

**Comment by RealJTG** [comment]
May be useful https://github.com/smore-inc/clippy.js

**Comment by davidmn** [comment]
"It looks like you're trying to resolve merge conflicts, would you like help?"

**Comment by martenbjork** [comment]
This is a terrible suggestion.

So I went ahead and implemented it right way!

![screen recording google chrome](https://user-images.githubusercontent.com/875708/41030820-75e17970-697f-11e8-891c-f7bec73dd2bb.gif)

**Comment by FredKSchott** [comment]
Hahahaha YES!!! Amazing
